### ISSUE TITLE
Num and Denum in fold change for a matrix dataset

### ISSUE THREAD

**Issue by parisashahnazari** [r-gregmisc/gtools#14]
Dear Dr Warnes,
I am dealing with changing my metabolomics datapints to fold change (matrix form in csv file) using gtools package.
I have confused  what is num and denom in my datasets, first I considered num as my disease group and denom as healthy ones but I faced with different size errors. Could you please help me in this regard?
Kind regards
Parisa

**Comment by bbolker** [comment]
closing, in the absence of clarification/reproducible example ...
