### ISSUE TITLE
orphaned package?

### ISSUE THREAD

**Issue by bbolker** [r-gregmisc/gtools#15]
Just querying status here because CRAN's page for `gtools` says `Maintainer: ORPHANED`. Don't know when that happened ... I would probably be willing to take on maintainership ...

**Comment by talgalili** [comment]
Hey @bbolker - I've gone through this with the gplots package.
I've contacted the author (@gwarnes-mdsol) and didn't get a reply before the package went offline. At some point I just moved the package to my own repo and reuploaded it to CRAN so it wouldn't be offline:
https://github.com/talgalili/gplots
And made sure to continue maintaining it.

I was approached after the fact suggesting me to move the package to this current repo, but didn't get a followup with support for doing it, so I've just continued the status quo as is.

I suggest you give this some time, but make sure that before the package goes off CRAN, to take ownership over it.
If you want help, feel free to add me to your repo (but no promises on my part)

Cheers,
T

**Comment by bbolker** [comment]
FWIW I have a cleaned-up version of the package ready to go at https://github.com/bbolker/gtools

**Comment by talgalili** [comment]
Great!
I suggest you email cran to ask when they'll remove the package
automatically so that you could step in before if need be.

**Comment by warnes** [comment]
Hi Everyone,

I am currently eyeballs deep in a project completely unrelated to R and will be for some time.

I would love to have help keeping the gregmisc packages up to date and well maintained, this is the primary reason I created the r-gregmisc GitHub repo project.

**Comment by arni-magnusson** [comment]
Hi Greg, Tal, and Ben.

As a regular user and contributor to the gregmisc collection of packages, I'm happy to hear that their level of maintenance is strengthening, thanks to Tal (gplots) and Ben (gtools) stepping forward. For what it's worth: and my axe!

**Comment by bbolker** [comment]
@warnes, if you have a chance to give me and Tal push (write) access to this repo we can maintain it here.

I did make some small development-related changes to `gtools` - in particular I removed the `renv` stuff (I think this is something that should stay on the developer's side/be in `.gitignore`). If you object to that you can let me know.

**Comment by bbolker** [comment]
version 3.9.3 on its way to CRAN.

**Comment by talgalili** [comment]
Yay!
